name: PAPA K.
favicon: null
layout_spectrum: 0.46229
typography_spectrum: 0.36729
title: PAPA K. INTERNATIONAL DELIVERY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#321d56'
    - '#b8c8d8'
    - '#8499c4'
    - '#4c4e89'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
