name: PAPA K.
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56905
title: PAPA K. STORE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff6d22'
    - '#234453'
    - '#2cbfa2'
    - '#ffb32a'
    - '#878b58'
  brandStrength: 0.506733636604622
  lightness: 0.4317996569443494
  saturation: 0.37104526651091874
  rhythmicContrast: 0.8386447487864643
purpose: []
